export enum ConfigName {
  SECRET_KEY = 'SECRET_KEY',
  NODE_ENV = 'NODE_ENV',
  BOT_TOKEN = 'BOT_TOKEN',

  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_NAME',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
}
