name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Git updates
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: git pull
      - name: Build docker entry
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make build
      - name: Stop and remove active container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make rm
      - name: Stop and remove Postgres container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make rm-postgres
      - name: Stop and remove Redis container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make rm-redis
      - name: Stop and remove Clickhouse container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make rm-clickhouse
      - name: Run Postgres container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make postgres
      - name: Run Redis container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make redis
      - name: Run Clickhouse container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make clickhouse
      - name: Run docker entry
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make run
