name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0
      - name: Stop and remove containers / images / networks
        uses: ./.github/actions/ssh-script
        with:
          script: |
            make rm || true
            make rmi || true
            make rm-network || true
      - name: Create network of Docker registry
        uses: ./.github/actions/ssh-script
        with:
          script: make create-network
      - name: Build docker entry
        uses: ./.github/actions/ssh-script
        with:
          script: make build
      - name: Build docker postgres
        uses: ./.github/actions/ssh-script
        with:
          script: make postgres
      - name: Build docker redis
        uses: ./.github/actions/ssh-script
        with:
          script: make redis
      - name: Create database migration
        uses: ./.github/actions/ssh-script
        with:
          script: make migration
      - name: Run docker entry
        uses: ./.github/actions/ssh-script
        with:
          script: make run
