name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker entry
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make build
      - name: Stop and remove active containers
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: |
            make rm
            make rm-redis
            make rm-postgres
            make rm-clickhouse
      - name: Run Postgres container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make postgres
      - name: Run Redis container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make redis
      - name: Run Clickhouse container
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make clickhouse
      - name: Run docker entry
        uses: ./.github/actions/ssh-script
        with:
          secrets: ${{ toJson(secrets) }}
          script: make run
